const booking =
    JSON.parse(
        localStorage.getItem("confirmedBooking")
    );


if (!booking) {

    alert("No confirmed booking found.");

    window.location.href =
        "../events/index.html";

} else {

    document.getElementById("eventName").textContent =
        booking.event.name;

    document.getElementById("ticketType").textContent =
        booking.ticketType;

    document.getElementById("attendeeName").textContent =
        booking.attendee.name;

    document.getElementById("eventDate").textContent =
        booking.eventDate;

    document.getElementById("eventTime").textContent =
        booking.event.time;

    document.getElementById("eventVenue").textContent =
        booking.event.venue;

    document.getElementById("eventStage").textContent = "07:00 PM";

    document.getElementById("amount").textContent =
        "₹" + Number(booking.price).toLocaleString("en-IN");

    document.getElementById("paymentMethod").textContent =
        booking.paymentMethod;


    // REAL TICKET ID GENERATED BY BACKEND

    document.getElementById("ticketId").textContent =
        booking.ticketId || booking.ticket_id;

}